source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'acts-as-taggable-on'
gem 'mysql2', '~> 0.2.6'
gem 'tabulous'
gem 'gmaps4rails'
gem 'devise'
gem 'gravatar_image_tag'
gem 'will_paginate'
gem 'awesome_nested_set'
gem 'simple_form'
gem 'paperclip'
gem "friendly_id", "~> 4.0.0.beta8"
gem 'workflow'
gem 'formtastic'
gem "geocoder"
gem 'jquery-rails'
gem 'jquery_datepicker'
gem 'kaminari'
gem 'mongrel'
